name: Cypress Trello Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start app
        working-directory: ./app
        run: npm i, npm start
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: 'http://localhost:3000'
