name: Cypress Trello Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          working-directory: ./app
          runTests: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run e2e Tests
        uses: cypress-io/github-action@v4
        with:
          wait-on: 'http://localhost:3000'
